### DISCUSSION TITLE
More control with Accesscontrol Videobuitenpost NHC 1 Bel - BL 550-22001

### DISCUSSION THREAD

**Discussion by Pitsaer** [joleys/niko-home-control-II#130] [Q&A]
Hello, 

Is it possible to have more control options with accesscontrol? 
In action I only see my strike opening and in sensors I have Call Answered, Call Pending and Decline call applied on all devices. And of course I have video streaming.

When my doorbell rings, I always go through the Niko app or my Niko screen (because I'm kind of obliged to...). But I'd like to use Home Assistant to do a Hangup at the very least.

If you have any info or ideas :-)

**Comment by tijsverkoyen** [comment]
To my knowledge all possible actions are exposed.
@joleys any idea if it is possible to hang up?

**Comment by nexus256** [comment]
In configuration.yaml add following shell commands. Make sure the door phone is connected to your network, not to the Niko controller module. Otherwise HA cannot communicate with the  door phone!


shell_command:
    doorphone_hangup: curl -u admin:123qwe http://192.168.0.3/api/v1/call_hangup
    doorphone_mute: curl -u admin:123qwe http://192.168.0.3/api/v1/mute_set?mute=tones_incoming
    doorphone_unmute: curl -u admin:123qwe http://192.168.0.3/api/v1/mute_set?mute=off

Reboot HA.

Create automation (example in attachment)




Sent from my Galaxy



-------- Original message --------
From: Tijs Verkoyen ***@***.***>
Date: 18/03/24 18:16 (GMT+01:00)
To: joleys/niko-home-control-II ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [joleys/niko-home-control-II] More control with Accesscontrol Videobuitenpost NHC 1 Bel - BL 550-22001 (Issue #125)


To my knowledge all possible actions are exposed.
@joleys<https://github.com/joleys> any idea if it is possible to hang up?

**Comment by tijsverkoyen** [comment]
@Pitsaer can you confirm this is working?
If so I will add it to the FAQ. Thx @nexus256

**Comment by nexus256** [comment]
Extra info:

- API handleiding: https://www.robintele.com/images/downloads/How-To_The_Robin_API_v3.6.0_NL.pdf
- Handleiding: https://www.robintele.com/images/downloads/Manual-Robin-SV-3211NL.pdf

**Comment by Pitsaer** [comment]
@tijsverkoyen Sorry for the late reply. I'll try it this week and get back to you :-) 
@nexus256 I don't see the example of your automation.
Have a nice evening.

**Comment by nexus256** [comment]
````yaml
alias: NHC - Voordeur verbreek call bij openen deur
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.routine_deurcontact_voordeur_start_active
    from: "off"
    to: "on"
condition: []
action:
  - service: shell_command.doorphone_hangup
    data: {}
mode: single
````

**Comment by Pitsaer** [comment]
It works great, thanks !
That way, when someone rings the doorbell, I get the picture of the street phone displayed on my dashboard, with a hangup button and a mute button :-)

````yaml
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - condition: state
        entity: sensor.poste_video_exterieur_call_status_01
        state: Idle
    card:
      show_current: true
      show_forecast: true
      type: weather-forecast
      entity: weather.buienradar
      forecast_type: daily
  - type: conditional
    conditions:
      - condition: state
        entity: sensor.poste_video_exterieur_call_status_01
        state: Ringing
    card:
      camera_view: live
      type: picture-glance
      entities:
        - entity: binary_sensor.sonette_call_pending
        - entity: binary_sensor.sonette_call_answered
      camera_image: camera.poste_video_exterieur
      aspect_ratio: '4:3'
      tap_action:
        action: navigate
        navigation_path: ''
  - type: conditional
    conditions:
      - condition: state
        entity: sensor.poste_video_exterieur_call_status_01
        state: Ringing
    card:
      type: horizontal-stack
      cards:
        - type: horizontal-stack
          cards:
            - type: custom:mushroom-template-card
              primary: hangup
              secondary: ''
              icon: mdi:radio
              tap_action:
                action: call-service
                service: shell_command.doorphone_hangup
                target: {}
              badge_color: ''
              icon_color: purple
        - type: horizontal-stack
          cards:
            - type: custom:mushroom-template-card
              primary: mute
              secondary: ''
              icon: mdi:radio
              tap_action:
                action: call-service
                service: shell_command.doorphone_mute
                target: {}
              badge_color: ''
              icon_color: red
````

Is there any chance of being able to pick up the phone directly and speak like in the Niko Home app or on the niko control screen?
