### DISCUSSION TITLE
Act temp from Touchswitch thermostat

### DISCUSSION THREAD

**Discussion by brett1996** [joleys/niko-home-control-II#146] [Q&A] [answered]
Hi,

I would like to use the room temp, i'm getting from the touchSwitch thermostat. 
But is seems that I'm only getting the setpoint entity.
I've found that it is possible to build a template sensor, but I don't have any experience in this.

Can someone help me with this. Or is is possible to make this available as entity ?

**Comment by brett1996** [comment, marked as answer]
I Fixed it myself by adding this in the config

```
template:
  - sensor:
      - name: WoonkamerTemperature
        unique_id: "0a7476cc-d6c1-40ba-8ae1-606518c3497f"
        device_class: Temperature
        state_class: measurement
        unit_of_measurement: "°C"
        state: "{{ float(state_attr('climate.woonkamer', 'current_temperature')) | round(1) }}"

      - name: BadkamerTemperature
        unique_id: "0a7576cc-d6c1-40ba-8ae1-606518c3497f"
        device_class: Temperature
        state_class: measurement
        unit_of_measurement: "°C"
        state: "{{ float(state_attr('climate.badkamer_db', 'current_temperature')) | round(1) }}"

      - name: Slaapkamer1Temperature
        unique_id: "0a7676cc-d6c1-40ba-8ae1-606518c3497f"
        device_class: Temperature
        state_class: measurement
        unit_of_measurement: "°C"
        state: "{{ float(state_attr('climate.slaapkamer_1_db', 'current_temperature')) | round(1) }}"

      - name: Slaapkamer2Temperature
        unique_id: "0a7776cc-d6c1-40ba-8ae1-606518c3497f"
        device_class: Temperature
        state_class: measurement
        unit_of_measurement: "°C"
        state: "{{ float(state_attr('climate.slaapkamer_2_db', 'current_temperature')) | round(1) }}"
```
