### ISSUE TITLE
Integrate Niko energy clamp

### ISSUE THREAD

**Issue by Gavergracht** [joleys/niko-home-control-II#13]
How can i read niko energy clamp? he is direlctly connectet to main niko home control and i cant see the device in the devices on HASS.

**Comment by joleys** [comment]
My installation has the 3-phase metering module (550-00803) and that is working.  Should be the same for the 1-phase model (550-00801).
I've defined some additional sensors in HA to get different counters for consumed and produced energy to feed the energy dashboard.  If interested I can share this configuration.  Currently I'm not able to include this functionality into the integration .

**Comment by joleys** [comment]
```
sensor:
  - platform: integration
    source: sensor.elektriciteitsmeting
    name: energy_elektriciteit
    unit_prefix: k
    round: 3
    method: left
  - platform: integration
    source: sensor.energie_productie
    name: energy_elektriciteit.productie
    unit_prefix: k
    round: 3
    method: left
  - platform: integration
    source: sensor.energie_consumptie
    name: energy_elektriciteit.consumptie
    unit_prefix: k
    round: 3
    method: left

utility_meter:
  energy_hourly:
    source: sensor.energy_elektriciteit
    net_consumption: true
    cycle: hourly
  energy_daily:
    source: sensor.energy_elektriciteit
    net_consumption: true
    cycle: daily
  energy_monthly:
    source: sensor.energy_elektriciteit
    net_consumption: true
    cycle: monthly
    
template:
  - sensor:
      - name: "Energie Consumptie"
        unit_of_measurement: "W"
        device_class: energy
        state: >-
            {% if states('sensor.elektriciteitsmeting') | float >= 0 %}
             {{ states('sensor.elektriciteitsmeting') | float }}
            {% else %}
              {{ 0 }}
            {% endif %}
  - sensor:
      - name: "Energie Productie"
        unit_of_measurement: "W"
        device_class: energy
        state: >-
            {% if states('sensor.elektriciteitsmeting') | float <= 0 %}
             {{ states('sensor.elektriciteitsmeting') | float | abs }}
            {% else %}
              {{ 0 }}
            {% endif %}
```
