### ISSUE TITLE
Adding more than 1 meter

### ISSUE THREAD

**Issue by 86hakan** [joleys/niko-home-control-II#8]
Do you know how to add more than one electricel meter?

I have tested to add more of this

    - platform: integration
        source: sensor.totalmatare
        name: energy_elektriciteit
        unit_prefix: k
        round: 3
        method: left
        
        source: sensor.solceller
        name: energy_solceller
        unit_prefix: k
        round: 3
        method: left

But not getting it to work. Any idé?

**Comment by joleys** [comment]
There are 2 parts to get 'integrations' (= totalizers) working.

```
sensor:
    - platform: integration
        source: sensor.elektriciteitsmeting
        name: energy_elektriciteit
        unit_prefix: k
        round: 3
        method: left
```

Where 'sensor.elektriciteitsmeting' is the actual sensor name as configured in your NHCII installation.  'Energy_elektriciteit' is the name of the integrated value.

```
utility_meter:
    energy_daily:
        source: sensor.energy_elektriciteit
        cycle: daily
    energy_monthly:
        source: sensor.energy_elektriciteit
        cycle: monthly
```

Here 'energy daily' and 'energy_monthly' are totalizers that will be reset resp. daily and monthly.  Other reset intervals are possible of course.

I'm not sure what you are trying to achieve, but hope this will help.
