### ISSUE TITLE
No connected sockets among entities 

### ISSUE THREAD

**Issue by flimofly** [joleys/niko-home-control-II#83]
Fresh install of Home Assistant and the NHC II integration.

I don't see the connected sockets (product id 170-33505) in the list of entities. They have been added via the Niko Home Control programming software ('addressed') and I can see them in the Energy tab in the Niko Home app.

I do see some inactive entities called ```binary_sensor.energyhome_report_instant_usage``` but these don't seem to be it.

Do I need to do something else (perhaps create a virtual device?) to make them show up in the integration?

**Comment by tijsverkoyen** [comment]
I have the same devices at home, and they appear in the integration.

Do you see other devices listed? Or is `binary_sensor.energyhome_report_instant_usage` the only one?
Are you sure the connection to the Niko controller is successfull? Did you use the hobby account?

**Comment by flimofly** [comment]
![Screenshot 2023-07-26 at 16 31 14](https://github.com/joleys/niko-home-control-II/assets/20085376/3d96852c-47e7-4f38-bee2-9fec93cb660e)

I see these ones. Do these match with how they appear in your installation?

**Comment by flimofly** [comment]
![Screenshot 2023-07-26 at 16 36 25](https://github.com/joleys/niko-home-control-II/assets/20085376/1bd321a7-bea7-4159-9938-b8c042795813)

one of them shows some activity. 

In the devices list I have my lights, video doorbell and shutters. These work fine.

**Comment by tijsverkoyen** [comment]
That is not a device list, see the steps in https://github.com/joleys/niko-home-control-II#i-need-to-see-the-device-list

**Comment by flimofly** [comment]
Ok, I have the settings in my configuration.yaml but where do I retrieve the logs? The full log from System>Logs does not contain a device list.

**Comment by tijsverkoyen** [comment]
Did you restart Home Assistant? 
Check if there is a file `home-assistant.log` in the same folder as `configuration.yaml`, in this log the device list will be present if you search for "Received device list:".

**Comment by tijsverkoyen** [comment]
@flimofly any update?

**Comment by flimofly** [comment]
The file `home-assistant.log` is present but contains only:
```
2023-07-28 13:19:06.658 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nhc2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-28 13:19:06.658 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-28 13:19:19.579 DEBUG (MainThread) [custom_components.nhc2] Connecting to 192.168.0.42 with 50f25849-c2db-4be7-9335-1e4c186f3a3a
2023-07-28 13:19:19.679 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.coco] Connected to MQTT broker
```

**Comment by flimofly** [comment]
full content of `configuration.yaml`:

```
# for home assistant debugging
logger:
      default: warning
      logs:
          custom_components.nhc2: debug

recorder:
  purge_keep_days: 30
  commit_interval: 3
  db_url: "postgresql://home-assistant:xxKO4Nat0Ex22hRapcHSePrY7PYgeI7c9hB492HkSJ9kKV9wKUpxW0F69WTOFM@home-assistant-cnpg-main-rw:5432/home-assistant?client_encoding=utf8"
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/16
```
